basePath: /
definitions:
  models.Category:
    properties:
      description:
        type: string
      id:
        type: integer
      name:
        type: string
    type: object
  models.CheckoutItem:
    properties:
      product_id:
        type: integer
      quantity:
        type: integer
    type: object
  models.CheckoutRequest:
    properties:
      items:
        items:
          $ref: '#/definitions/models.CheckoutItem'
        type: array
    type: object
  models.Product:
    properties:
      category_id:
        type: integer
      category_name:
        type: string
      id:
        type: integer
      name:
        type: string
      price:
        type: number
      stock:
        type: integer
    type: object
  models.Transaction:
    properties:
      created_at:
        type: string
      details:
        items:
          $ref: '#/definitions/models.TransactionDetail'
        type: array
      id:
        type: integer
      total_amount:
        type: integer
    type: object
  models.TransactionDetail:
    properties:
      id:
        type: integer
      product_id:
        type: integer
      product_name:
        type: string
      quantity:
        type: integer
      subtotal:
        type: integer
      transaction_id:
        type: integer
    type: object
  util.Category:
    properties:
      id:
        type: integer
      name:
        type: string
    type: object
  util.JSONResponse:
    properties:
      data: {}
      message:
        type: string
    type: object
  util.ProductResp:
    properties:
      category:
        $ref: '#/definitions/util.Category'
      id:
        type: integer
      name:
        type: string
      price:
        type: number
      stock:
        type: integer
    type: object
info:
  contact: {}
  description: REST API for product and category
  title: Simple CRUD API
  version: "1.0"
paths:
  /api/v1/categories:
    get:
      description: Retrieve all categories
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/util.JSONResponse'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/models.Category'
                  type: array
              type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/util.JSONResponse'
      summary: Get all categories
      tags:
      - categories
    post:
      consumes:
      - application/json
      description: Create a new category
      parameters:
      - description: Category payload
        in: body
        name: category
        required: true
        schema:
          $ref: '#/definitions/models.Category'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            allOf:
            - $ref: '#/definitions/util.JSONResponse'
            - properties:
                data:
                  $ref: '#/definitions/models.Category'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/util.JSONResponse'
      summary: Create new category
      tags:
      - categories
  /api/v1/categories/{id}:
    delete:
      description: Delete category by ID
      parameters:
      - description: Category ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/util.JSONResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/util.JSONResponse'
      summary: Delete category
      tags:
      - categories
    get:
      description: Get category detail by ID
      parameters:
      - description: Category ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/util.JSONResponse'
            - properties:
                data:
                  $ref: '#/definitions/models.Category'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/util.JSONResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/util.JSONResponse'
      summary: Get category by ID
      tags:
      - categories
    put:
      consumes:
      - application/json
      description: Update category by ID
      parameters:
      - description: Category ID
        in: path
        name: id
        required: true
        type: integer
      - description: Category payload
        in: body
        name: category
        required: true
        schema:
          $ref: '#/definitions/models.Category'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/util.JSONResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/util.JSONResponse'
      summary: Update category
      tags:
      - categories
  /api/v1/checkout:
    post:
      consumes:
      - application/json
      description: Create transaction from cart items and update product stock
      parameters:
      - description: Checkout payload
        in: body
        name: checkout
        required: true
        schema:
          $ref: '#/definitions/models.CheckoutRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Transaction'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Checkout transaction
      tags:
      - transactions
  /api/v1/products:
    get:
      description: Get list of products with category
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/util.JSONResponse'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/util.ProductResp'
                  type: array
              type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/util.JSONResponse'
      summary: Get all products
      tags:
      - products
    post:
      consumes:
      - application/json
      description: Create new product
      parameters:
      - description: Product payload
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/models.Product'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            allOf:
            - $ref: '#/definitions/util.JSONResponse'
            - properties:
                data:
                  $ref: '#/definitions/util.ProductResp'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/util.JSONResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/util.JSONResponse'
      summary: Create product
      tags:
      - products
  /api/v1/products/{id}:
    delete:
      description: Delete product by ID
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/util.JSONResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/util.JSONResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/util.JSONResponse'
      summary: Delete product
      tags:
      - products
    get:
      description: Get product detail with category
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/util.JSONResponse'
            - properties:
                data:
                  $ref: '#/definitions/util.ProductResp'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/util.JSONResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/util.JSONResponse'
      summary: Get product by ID
      tags:
      - products
    put:
      consumes:
      - application/json
      description: Update product by ID
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: integer
      - description: Product payload
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/models.Product'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/util.JSONResponse'
            - properties:
                data:
                  $ref: '#/definitions/util.ProductResp'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/util.JSONResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/util.JSONResponse'
      summary: Update product
      tags:
      - products
swagger: "2.0"
